### ISSUE TITLE
Initialize Web Wallet backend

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-wallet-backend#1]
- [x]  REST API using JavaLin
- [x]  Connect WebWallet frontend with backend via REST API
- [x]   Mocked-User Management (one hard-coded user is sufficient)
- [x]   Populate the users credential store with two credentials
- [x]   List credentials in UI
- [x]   Show details of credentials in UI
- [x]   Present credentials button -> redirect to verifier
- [x]   Simulate Verifier service, which verifiers the VP
 - [x]   - Start screen
- [x]    - Verification screen

**Comment by severinstampler** [comment]
done
