### ISSUE TITLE
Ports not accessible when running the Docker container

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-wallet-backend#10]
This command does not expose the ports:
docker run -it -p 8080:8080 waltid/ssikit-wallet-backend

However, docker-compose is working fine.

Please either fix this or remove this command from the READMe

**Comment by severinstampler** [comment]
the service binds to the loopback interface by default, and therefore the port isn't reachable when using the docker container.
I chnaged the default binding address to the public interface in the docker container, which resolves the issue.
