### ISSUE TITLE
I try to build on my localhost..but something wrong

### ISSUE THREAD

**Issue by bigrender** [walt-id/waltid-wallet-backend#13]
![이미지 070](https://user-images.githubusercontent.com/440469/152679609-8a42377f-ba2d-47f4-be4f-c15515761d3e.png)
I try to build my own computer(window),, 

I launched backend with docker...then I clone the frontend project, walllet,issue,verify, but when i try to make add credential.. there is error.
>> this 500 error, http://localhost:3000/api/wallet/siopv2/issuer/metadata?issuerId=walt.id

I would like to know how to fix this ..

![이미지 070](https://user-images.githubusercontent.com/440469/152679609-8a42377f-ba2d-47f4-be4f-c15515761d3e.png)

**Comment by atuffreau-bcd** [comment]
I get the same error (with Windows as well) when running the full stack with Docker compose

**Comment by YassineOuahidi** [comment]
I get the same error with Docker compose

**Comment by severinstampler** [comment]
I fixed the docker-compose setup with rev: e8ad8d9d5ec8c834d9f9d580c04632b00e78d81c

@bigrender did you run the backend using the docker-compose up command, or did you run it individually using docker run?
In any case, I managed to make it work in both cases, so if I know more details about how you're running it, I may be able to tell what's wrong.

**Comment by severinstampler** [comment]
fixed docker-compose configuration on windows: fe076fef0434dd2e8222c06f53cc7fa850a9e5bb

**Comment by bigrender** [comment]
Thanks

2022년 3월 1일 (화) 오후 7:39, Severin Stampler ***@***.***>님이 작성:
