### ISSUE TITLE
Credential issuance fails when started from the issuer portal

### ISSUE THREAD

**Issue by ohylli** [walt-id/waltid-wallet-backend#15]
The issuance flow seems not to work when it is started from the issuer portal:
1. I log in to the issuer
2. I choose university diploma and and then confirm
3. I am redirected to the wallet and log in.
4. I am asked to confirm "Empty presentation requested" and I accept and see the
   following error in chrome dveloper tools

```
Error
xhr.js:210 POST https://wallet.waltid.org/api/wallet/siopv2/fulfillPassiveIssuance?sessionId=78fbedcf-a0ab-4a58-b40c-0b8c752b8b10 500
Error
vue.runtime.esm.js:1897 Error: Request failed with status code 500
```

This happens both with the version hosted by walt.id and if I run the demo
locally. When ran locally I see the following in the backend console output:
```
[JettyServerThreadPool-28] ERROR OIDC4VPService - Got error response from SIOP endpoint: 404: Not found
```

When using the newer way of requesting the issuance from the walled the issuing
works but I assume the old way should also work. It has worked for me before
though I was then using a version that did not yet have the feature where the
wallet could request issuance.

**Comment by severinstampler** [comment]
problem solved with https://github.com/walt-id/waltid-wallet-backend/commit/ceb504fd8b01c323f8183b5391f41d2966ee93cc
