### ISSUE TITLE
DID Registration within the wallet

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-wallet-backend#6]
In the scope of the signup-process a DID key should be created on the fly.

If a user wants to onboard the EBSI ecosystem (or potentially another one in future) the user should open the "settings"-page of the wallet. On the settings-page is should be possible to set a default-did (drop-down menu). In case there is no did:ebsi yet available there shoudl appear a button "Onboard EBSI", where the EBSI-onboarding flow is initiated. Once this is completed the user can set the default DID  from did:key to did:ebsi.

**Comment by severinstampler** [comment]
necessary APIs are implemented. UI changes pending.
